--1. book xpdlqmf todtjd 

DROP TABLE BOOK;
CREATE TABLE BOOK 
( SEQUENCE NUMBER
, ISBN      VARCHAR2 (13)
, TITLE      VARCHAR2 (100)
, AUTHOR     VARCHAR2 (30)
, COMPANY    VARCHAR2 (30)
, TOTAL_PAGE NUMBER
, PRICE      NUMBER(7)
, QUANTITY   NUMBER(4)
, REG_DATE DATE DEFAULT sysdate
, MOD_DATE DATE 
, CONSTRAINT PK_BOOK PRIMARY KEY (SEQUENCE)
, CONSTRAINT UQ_BOOK_ISBN UNIQUE (ISBN) 
);



--1건 조회 



--전체 칼럼 조회 

--INSERT 구문 

--UPDATE 구문 

